[[docs]]
  name = "Invigilation"
  weight = 10
  identifier = "invigilation"
  url = "/docs/invigilation/"

[[docs]]
  name = "Help"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

# [[docs]]
#   name = "Lorem"
#   weight = 70
#   identifier = "lorem"
#   url = "/docs/lorem/"

[[main]]
  name = "Docs"
  url = "/docs/quick-start/quick-start/"
# url = "/docs/1.0/prologue/introduction/"
  weight = 10

# [[main]]
#   name = "Tutorial"
#   url = "/tutorial/lorem/ipsum/"
#   weight = 15

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[footer]]
  name = "Visit Exam Display website"
  url = "https://www.examdisplay.com"
  weight = 10

[[footer]]
  name = "Privacy"
  url = "/privacy-policy/"
  weight = 10
